# Generated by Django 3.2.15 on 2022-10-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20221019_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_gbfrps', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='image_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
