# Generated by Django 3.2.15 on 2022-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20221019_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='slug',
        ),
    ]
