# Generated by Django 3.2.15 on 2022-10-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contacts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='image_filter',
        ),
    ]
