# Generated by Django 3.2.15 on 2022-10-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imessages', '0006_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image_filter',
            field=models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=12),
        ),
    ]
